// Offline association lexicon for the developer mock AI: picture description → words it suggests.
// Agent-written associations for the built-in concept banks and the Grandville deck.
// Real models never use this.

export const MOCK_LEXICON: Readonly<Record<string, string>> = {
  "an elephant whose trunk is an umbrella and whose tail is a propeller": "elephant umbrella propeller trunk flight shelter dumbo circus",
  "a snail whose shell is a lighthouse": "snail lighthouse shell beacon slow coast patience keeper",
  "a giraffe whose neck is a wooden ladder": "giraffe ladder wooden climb height savanna promotion rungs",
  "an octopus whose tentacles are garden hoses": "octopus hose garden water sprinkler tentacle multitask kraken",
  "a peacock whose tail feathers are playing cards": "peacock cards feathers poker casino vanity bluff flush",
  "an owl with alarm clocks for eyes": "owl clock alarm wisdom time night insomnia vigilant",
  "a turtle carrying a castle on its back": "turtle castle tower shell home slow burden kingdom",
  "a whale whose spout is a fountain of coins": "whale coins fountain money treasure ocean jackpot fortune",
  "a cat whose tail is a feather duster": "cat duster feather cleaning chores housekeeping tidy spotless",
  "a goldfish swimming inside a light bulb": "goldfish bulb glass water idea bright aquarium memory",
  "a rabbit popping out of a toaster": "rabbit toaster toast breakfast surprise magic bunny pop",
  "a penguin riding a unicycle on a tightrope": "penguin unicycle tightrope balance circus acrobat risk daredevil",
  "a hedgehog whose spines are pencils": "hedgehog pencils spines school drawing sharp prickly stationery",
  "a crocodile with a zipper down its back": "crocodile zipper leather handbag costume reptile disguise fashion",
  "a flamingo standing on a pogo stick": "flamingo pogo pink bounce jump balance spring tropical",
  "a bee whose wings are helicopter rotors": "bee helicopter rotor wings buzz hover honey drone",
  "a spider knitting a scarf with eight needles": "spider knitting scarf needles yarn web craft arachne",
  "a dog wearing an old diving helmet": "dog helmet brass diver underwater explorer depth vintage",
  "a bat hanging upside down from a chandelier": "bat chandelier crystal ballroom night vampire gothic dracula",
  "a camel whose humps are hot air balloons": "camel balloon desert humps flight caravan sahara float",
  "a horse with roller skates instead of hooves": "horse skates wheels rink speed racing disco gallop",
  "a crab whose claws are scissors": "crab scissors claws beach snip pinch barber cancer",
  "a lion whose mane is a sunflower": "lion sunflower mane petals yellow pride king dandelion",
  "a bird nesting inside a top hat": "bird nest hat eggs magician gentleman shelter dapper",
  "a sloth hanging from a ceiling fan": "sloth fan ceiling lazy spinning dizzy jungle procrastinate",
  "a squirrel hoarding light bulbs": "squirrel bulbs acorns hoard ideas winter stockpile inspiration",
  "a chameleon blending into a chessboard": "chameleon chess squares camouflage disguise strategy invisible checkmate",
  "a swan made of folded newspaper": "swan newspaper origami paper headlines elegance ballet folding",
  "a frog using a mushroom as an umbrella": "frog mushroom umbrella rain forest shelter toadstool fairytale",
  "a mouse driving a cheese wheel like a car": "mouse cheese wheel driver race journey cartoon swiss",
  "a teapot that is also a hot air balloon": "teapot balloon steam tea flight voyage adventure teatime",
  "a light bulb with a tiny thunderstorm inside": "bulb storm lightning thunder electricity idea brainstorm energy",
  "an hourglass filled with ocean waves": "hourglass waves ocean sand time tide eternity beach",
  "a grand piano whose keys form a staircase": "piano staircase keys steps music scale climb melody",
  "a pocket watch melting over a cactus": "watch cactus melting desert time heat dali surreal",
  "a sneaker with bird wings": "sneaker wings shoe feathers speed running mercury freedom",
  "a toaster launching a rocket": "toaster rocket launch kitchen space breakfast countdown pop",
  "an umbrella raining upwards": "umbrella rain droplets gravity weather reverse paradox contrary",
  "a giant key that is also a guitar": "key guitar strings lock music tune unlock chord",
  "a chess knight galloping out of an open book": "knight chess book pages horse story imagination novel",
  "a coffee cup with a whirlpool inside": "coffee cup whirlpool swirl morning vortex caffeine maelstrom",
  "a birdcage holding a cloud": "birdcage cloud bars sky captive freedom dream weather",
  "a ladder leaning against the crescent moon": "ladder moon crescent night climb stars ambition dream",
  "a candle whose flame is a goldfish": "candle goldfish flame wax glow elements paradox vigil",
  "a typewriter typing out butterflies": "typewriter butterflies keys paper writing poetry inspiration metamorphosis",
  "a padlock with a tiny front door in it": "padlock door keyhole home security privacy secret burglar",
  "a telescope made of stacked teacups": "telescope teacups porcelain stack astronomy tea stargazing whimsy",
  "a magnifying glass showing a tiny city": "lens city glass skyline detective miniature microcosm scrutiny",
  "a pencil launching like a rocket": "pencil rocket launch eraser school creativity ambition liftoff",
  "a crown made of forks and spoons": "crown forks spoons cutlery royalty banquet privilege kitchen",
  "a mailbox with a small dragon living inside": "mailbox dragon letters postman fire fantasy delivery lair",
  "an anchor tied to a party balloon": "anchor balloon rope party weight float burden hope",
  "a broom sweeping up stars": "broom stars dustpan night cosmos cleaning witch stardust",
  "a compass whose needle is a fish": "compass fish needle north navigation direction sailor bearings",
  "an alarm clock with legs running away": "clock alarm legs running time morning deadline fleeting",
  "a paintbrush painting its own shadow": "paintbrush shadow paint canvas art identity escher reflection",
  "a television with real water spilling out of it": "television water screen flood broadcast stream immersion leak",
  "a pair of scissors cutting a cloud in half": "scissors cloud blades sky cut weather divide separation",
  "a trumpet blowing soap bubbles": "trumpet bubbles soap brass music jazz fanfare playful",
  "a bathtub sailing as a boat": "bathtub boat sail soap voyage bathtime adventure odyssey",
  "a refrigerator with a snowy mountain inside": "fridge mountain snow peak cold winter everest frost",
  "a vending machine selling planets": "vending planets coins buttons space cosmos commerce consumerism",
  "an armchair growing tree roots": "armchair roots tree cushion comfort nature homebody inertia",
  "a book with a waterfall pouring from its pages": "book waterfall pages water story imagination flow knowledge",
  "an old radio sprouting flowers": "radio flowers antenna bloom music spring nostalgia airwaves",
  "a camera whose lens is a human eye": "camera eye lens photo vision surveillance iris witness",
  "an envelope with wings": "envelope wings letter feathers flight message airmail pigeon",
  "a boot that is a little house with a chimney": "boot cottage chimney smoke home cozy nursery fairytale",
  "a teacup with a sailing ship in a storm": "teacup ship storm waves sailing tempest drama overreaction",
  "a light bulb hatching from an egg": "bulb egg shell hatch idea invention genesis brainchild",
  "a sandwich with piano keys as the filling": "sandwich piano keys bread lunch music ivory jam",
  "a fishbowl worn as a space helmet": "fishbowl helmet astronaut glass space exploration improvise cosplay",
  "a lighthouse that is a giant pencil": "lighthouse pencil coast graphite beacon writing guidance lead",
  "a castle built on a cloud tied down with a rope": "castle cloud rope sky tether fantasy daydream utopia",
  "a windmill whose blades are spoons": "windmill spoons blades wind cutlery dutch stir quixote",
  "a cottage walking on chicken legs": "cottage chicken legs hut forest witch folklore russian",
  "a skyscraper made of stacked books": "skyscraper books stack city library knowledge literacy babel",
  "a pyramid made of ice cream scoops": "pyramid scoops vanilla dessert egypt summer pharaoh sundae",
  "a bridge made of piano keys": "bridge piano keys river music crossing harmony ivory",
  "a volcano erupting popcorn": "volcano popcorn lava kernels cinema snack explosion blockbuster",
  "an island on the back of a whale": "island whale palm ocean voyage illusion sinbad leviathan",
  "a snow globe with a tiny city inside": "globe city snow glass winter souvenir christmas bubble",
  "a tree house inside a giant mushroom": "treehouse mushroom fungus forest fairy hideout childhood smurf",
  "a door standing alone in the ocean": "door ocean waves horizon portal threshold opportunity narnia",
  "a spiral staircase climbing into the clouds": "staircase spiral clouds steps heaven ascension sky afterlife",
  "a carousel with fish instead of horses": "carousel fish fairground spin ocean carnival whirl aquarium",
  "a tent made of one giant leaf": "tent leaf camping jungle green shelter survival wilderness",
  "a fountain pouring out of a teapot": "fountain teapot spout water pouring tea abundance hospitality",
  "a knight in armor riding a giant snail": "knight snail armor lance medieval slow quest chivalry",
  "an astronaut fishing from the moon": "astronaut moon fishing rod space patience lunar dreamworks",
  "a deep sea diver walking a dog on the seabed": "diver dog leash seabed ocean walkies underwater loyalty",
  "a chef juggling planets": "chef planets juggling toque cosmos cooking multitasking creation",
  "a magician pulling a dragon out of a hat": "magician dragon hat wand magic trick illusion showman",
  "a scarecrow conducting an orchestra of crows": "scarecrow crows baton field conductor symphony harvest irony",
  "a ballerina spinning on a record player": "ballerina record vinyl tutu dance pirouette melody spin",
  "a king whose crown is a birdcage": "king crown birdcage throne royalty captivity gilded burden",
  "a robot watering a single flower": "robot flower watering garden care nurture tenderness hope",
  "a detective inspecting a giant fingerprint": "detective fingerprint magnifier clue mystery crime sherlock evidence",
  "a pirate looking through a baguette telescope": "pirate baguette telescope bread ship treasure french lookout",
  "a mermaid relaxing in a bathtub": "mermaid bathtub tail bubbles relax pamper fairytale siren",
  "a snowman sunbathing on a beach": "snowman beach sunglasses sand melting vacation olaf doomed",
  "a samurai slicing a flying watermelon": "samurai watermelon katana juice japan precision ninja discipline",
  "a mime trapped inside a light bulb": "mime bulb glass silence trapped idea invisible claustrophobia",
  "a firefighter hosing down a sleepy dragon": "firefighter dragon hose water fire rescue extinguish slumber",
  "a sumo wrestler balancing on a teacup": "sumo teacup porcelain japan balance fragile heavyweight gravity",
  "a wizard whose beard is a waterfall": "wizard beard waterfall staff magic wisdom merlin gandalf",
  "a cowboy riding a giant rubber duck": "cowboy duck rubber lasso western rodeo bathtime toy",
  "a mountain climber scaling a stack of pancakes": "climber pancakes syrup rope breakfast summit challenge everest",
  "a pineapple wearing a crown and a cape": "pineapple crown cape tropical royalty king superhero majesty",
  "a slice of watermelon used as a boat": "watermelon boat rind seeds summer picnic voyage canoe",
  "a strawberry wearing roller skates": "strawberry skates wheels fruit rink speed disco retro",
  "a donut used as a life ring": "donut lifebuoy sprinkles water rescue sweet drowning comfort",
  "an egg cracking open to reveal a planet": "egg planet shell yolk birth cosmos creation genesis",
  "a carrot launching like a rocket": "carrot rocket launch vegetable garden space rabbit incentive",
  "a banana used as a telephone": "banana telephone receiver call fruit yellow prank silly",
  "an ice cream cone with a volcano on top": "cone volcano scoop lava dessert eruption meltdown contrast",
  "a burger with a jungle growing inside": "burger jungle lettuce bun rainforest wilderness vegan overgrown",
  "a lemon that is a submarine": "lemon submarine periscope citrus ocean sour yellow beatles",
  "a fork twirling a spaghetti tornado": "fork spaghetti tornado pasta twirl italian whirlwind chaos",
  "a cake shaped like a castle besieged by ants": "cake castle ants frosting siege army invasion birthday",
  "a pizza used as a wall clock": "pizza clock slices pepperoni time hunger dinnertime delivery",
  "a wedge of cheese that is a mountain with climbers": "cheese mountain climbers holes swiss alps summit expedition",
  "a cup of tea with an iceberg floating in it": "tea iceberg cup saucer titanic chill tip arctic",
  "a bicycle whose wheels are pizzas": "bicycle pizza wheels pedal delivery courier italian pepperoni",
  "a submarine whose periscope is a giraffe": "submarine giraffe periscope neck ocean lookout spy safari",
  "a sailboat with a sail made of a newspaper": "sailboat newspaper sail headlines voyage news origami current",
  "a steam train whose carriages are books": "train books steam railway journey reading library chapters",
  "a hot air balloon that is a jellyfish": "balloon jellyfish tentacles sky float drift ethereal translucent",
  "a car walking on legs instead of wheels": "car legs walking vehicle traffic pedestrian flintstones commute",
  "a helicopter whose rotor is a ceiling fan": "helicopter fan rotor blades spin breeze flight whirlybird",
  "a skateboard pulled by snails": "skateboard snails slime wheels slow patience irony sluggish",
  "a tractor plowing the clouds": "tractor clouds plow farm sky harvest furrow rainmaker",
  "a paper airplane with a jet engine": "airplane paper jet engine flight speed upgrade turbo",
  "a shopping cart with sails": "cart sails shopping supermarket wind voyage groceries consumerism",
  "a rowing boat floating in the sky on a balloon": "rowboat balloon oars sky float voyage dream escapism",
  "a tree whose leaves are light bulbs": "tree bulbs leaves branches electricity ideas innovation enlightenment",
  "a cactus wearing boxing gloves": "cactus gloves boxing spines desert fighter prickly knockout",
  "a cloud raining keys": "cloud keys rain sky locks access windfall opportunity",
  "a rainbow pouring out of a faucet": "rainbow faucet colors sink spectrum pride flow optimism",
  "a sunflower whose center is a clock face": "sunflower clock petals hours summer seasons growth dandelion",
  "a mountain with a zipper opening up": "mountain zipper peak rock opening hidden reveal tectonic",
  "the moon being peeled like an orange": "moon orange peel citrus night phases lunar eclipse",
  "a tornado made of books": "tornado books pages storm library knowledge chaos literature",
  "an ocean wave shaped like a hand": "wave hand ocean surf fingers greeting poseidon farewell",
  "a flower growing out of an old boot": "flower boot soil bloom growth garden resilience renewal",
  "a leaf whose veins are city streets": "leaf city streets veins map urban network ecosystem",
  "a snowflake used as a wagon wheel": "snowflake wagon wheel winter ice frontier pioneer sleigh",
  "a guitar with a fishing reel": "guitar reel fishing strings music line hook catchy",
  "a drum kit made of pots and pans": "drums pots pans kitchen rhythm percussion racket improvise",
  "a violin whose bow is a fishing rod": "violin bow rod strings fishing classical catch orchestra",
  "a saxophone blooming with flowers": "saxophone flowers brass bloom jazz spring melody garden",
  "a gramophone horn that is a giant seashell": "gramophone seashell horn vinyl music ocean echo nostalgia",
  "a microphone sprouting roots": "microphone roots soil stage voice singer grassroots origins",
  "headphones made of a rainbow": "headphones rainbow colors music sound spectrum listening harmony",
  "a harp whose strings are falling rain": "harp rain strings droplets music angel lullaby melancholy",
  "a soccer ball hatching from an egg": "soccer egg shell hatch goal sport rookie talent",
  "a bowling pin wearing a top hat": "bowling pin hat alley strike gentleman dapper fancy",
  "a basketball hoop on top of a lighthouse": "basketball hoop lighthouse coast beacon sport dunk longshot",
  "a chessboard floating on the sea": "chessboard sea waves pieces strategy adrift stalemate raft",
  "a tennis racket used as a snowshoe": "tennis racket snowshoe snow winter hiking resourceful wimbledon",
  "a boxing glove with a bird nest inside": "boxing glove nest bird eggs fighter peace gentleness",
  "a golf ball that is a tiny planet with a flag": "golf ball planet flag dimples moon conquest astronaut",
  "a trophy cup overflowing with spaghetti": "trophy spaghetti cup pasta champion italian feast overflow",
  "a computer mouse with a real mouse tail": "mouse computer tail cursor click rodent technology wordplay",
  "a robot arm writing with a quill pen": "robot quill arm ink calligraphy automation author tradition",
  "a satellite dish catching raindrops": "satellite dish raindrops antenna signal weather reception forecast",
  "a battery powering a sunflower": "battery sunflower energy power solar growth charge renewable",
  "a horseshoe magnet pulling down the moon": "magnet moon horseshoe gravity attraction tides night ambition",
  "a light switch on the trunk of a tree": "switch tree trunk bark electricity nature control ecology",
  "a laptop whose screen is a window to the sea": "laptop sea screen window waves horizon surfing wanderlust",
  "a smartphone with a garden growing on it": "smartphone garden plants screen growth digital detox apple",
  "a dragon whose wings are umbrellas": "dragon umbrellas wings rain flight fantasy shelter drizzle",
  "a unicorn whose horn is an ice cream cone": "unicorn cone horn sprinkles fantasy dessert whimsy sweet",
  "a genie rising out of a coffee pot": "genie coffee pot steam wishes caffeine lamp arabian",
  "a ghost wearing a raincoat and rubber boots": "ghost raincoat boots rain puddle spooky halloween invisible",
  "a giant chess pawn wearing a crown": "pawn crown chess board promotion royalty underdog ambition",
  "a crystal ball with a storm inside": "crystal ball storm lightning fortune prophecy omen foreboding",
  "a treasure chest overflowing with stars": "treasure chest stars lid pirate cosmos riches wishes",
  "a phoenix rising out of a toaster": "phoenix toaster flames toast rebirth breakfast comeback ashes",
  "a castle inside a teacup": "castle teacup porcelain turret tea kingdom miniature fairytale",
  "a time machine made from a grandfather clock": "clock pendulum grandfather time travel history future tardis",
  "an owl perched on a branch at dusk": "owl branch feathers dusk night wisdom hoot athena",
  "a jellyfish glowing in dark water": "jellyfish tentacles glow ocean abyss bioluminescence ethereal neon",
  "a red fox curled up in snow": "fox snow tail winter cozy cunning fur firefox",
  "a peacock displaying its tail": "peacock feathers tail plumage pride vanity courtship iridescent",
  "a chameleon on a twig": "chameleon twig lizard camouflage color disguise adaptable karma",
  "a humpback whale breaching": "whale humpback ocean splash leap majesty song moby",
  "a hummingbird drinking from a flower": "hummingbird flower nectar beak hover sweetness pollinate blur",
  "a sleeping cat on a windowsill": "cat windowsill nap sunshine cozy lazy purr sunday",
  "a pack of wolves howling at the moon": "wolves moon howl pack night wilderness werewolf loyalty",
  "an elephant crossing a river": "elephant river trunk herd safari migration memory ivory",
  "a penguin sliding on ice": "penguin ice slide belly antarctic waddle tuxedo glacier",
  "a tortoise with moss on its shell": "tortoise moss shell slow ancient patience fable longevity",
  "a flamingo standing on one leg": "flamingo pink leg balance lagoon tropical yoga lawn",
  "a honeybee on a sunflower": "bee sunflower pollen nectar buzz summer hive busy",
  "a spider web covered in dew": "web spider dew silk morning trap intricate charlotte",
  "a lion resting on a rock": "lion rock mane savanna pride king royalty jungle",
  "a giraffe eating from a tall tree": "giraffe neck acacia leaves savanna height reach stretch",
  "a goldfish in a round bowl": "goldfish bowl water pet glass orange memory captive",
  "a raven on a fence post": "raven fence black feather omen gothic nevermore dusk",
  "a snail climbing a mushroom": "snail mushroom shell slime slow climb forest fairytale",
  "a polar bear on drifting ice": "polar bear floe arctic melting climate stranded white",
  "an octopus holding a seashell": "octopus tentacle shell ocean ink clever collector kraken",
  "a monarch butterfly on a leaf": "butterfly monarch leaf wings migration metamorphosis transformation orange",
  "a parrot with bright feathers": "parrot feathers tropical colorful mimic pirate jungle chatter",
  "a camel in the desert": "camel desert hump sand caravan thirst nomad oasis",
  "a rabbit in tall grass": "rabbit grass meadow ears hiding spring burrow easter",
  "a seahorse among coral": "seahorse coral reef ocean tropical camouflage father mythical",
  "a bat hanging upside down in a cave": "bat cave upside wings dark nocturnal vampire echo",
  "a swan gliding on a lake": "swan lake feathers glide grace elegance ballet duckling",
  "a dog catching a frisbee": "dog frisbee park jump fetch play catch loyalty",
  "a frog on a lily pad": "frog lily pond green leap croak prince tadpole",
  "a horse galloping through surf": "horse surf beach gallop freedom wild mane spray",
  "a sloth hanging from a branch": "sloth branch rainforest slow lazy nap relax sin",
  "a squirrel holding an acorn": "squirrel acorn oak nut hoard autumn winter savings",
  "a shark fin cutting through waves": "shark fin waves ocean danger predator jaws menace",
  "a firefly glowing in the night": "firefly glow night summer light magic childhood lantern",
  "a crab on a sandy beach": "crab beach sand claw shell tide sideways crabby",
  "a dragonfly over a pond": "dragonfly pond wings hover summer flight shimmer fleeting",
  "a volcano erupting at night": "volcano lava eruption fire ash magma fury inferno",
  "a rainbow over green hills": "rainbow hills green spectrum colors hope promise leprechaun",
  "a giant redwood forest": "redwood forest trunk giant ancient tall timber cathedral",
  "a frozen waterfall": "waterfall ice frozen icicle winter stillness cascade paused",
  "a lightning storm over the plains": "lightning storm thunder plains electricity power bolt wrath",
  "a desert with rippling sand dunes": "desert dunes sand ripple wind heat mirage wilderness",
  "a coral reef full of fish": "coral reef fish snorkel tropical diversity ecosystem aquarium",
  "the northern lights over mountains": "aurora lights mountains sky arctic green borealis wonder",
  "a single cactus flower in bloom": "cactus flower bloom desert spines resilience rare prickly",
  "a field of sunflowers": "sunflower field yellow petals summer sunshine harvest cheerful",
  "an iceberg floating in the sea": "iceberg sea ice arctic hidden danger tip titanic",
  "autumn leaves falling in a park": "leaves autumn park bench fall season change nostalgia",
  "a tornado on the horizon": "tornado funnel horizon prairie storm chaos destruction whirlwind",
  "a crystal cave glittering": "crystal cave quartz gems glitter underground treasure enchanted",
  "a quiet bamboo grove": "bamboo grove green stalks panda calm zen meditation",
  "cherry blossoms in spring": "cherry blossom pink petals spring renewal fleeting japan",
  "a solar eclipse": "eclipse sun moon shadow corona darkness alignment omen",
  "a meteor shower over a lake": "meteor shower stars lake reflection cosmos wish night",
  "a tide pool with starfish": "starfish tide pool rocks shore anemone explore treasure",
  "a giant ocean wave curling": "wave ocean surf curl swell power tsunami barrel",
  "a mossy stone in a stream": "moss stone stream water flow tranquil patience rolling",
  "a snowflake under magnification": "snowflake crystal ice microscope winter symmetry unique fragile",
  "a full moon behind clouds": "moon clouds night lunar glow mystery werewolf howl",
  "a lone tree on a hill": "tree hill silhouette landscape solitude lonely steadfast wallpaper",
  "a misty swamp at dawn": "swamp mist fog dawn marsh eerie mystery ogre",
  "a canyon with layered red rock": "canyon rock red layers erosion time geology grand",
  "a geyser erupting": "geyser steam spout eruption pressure boiling volcanic faithful",
  "a garden of roses": "rose garden thorns petals romance love beauty valentine",
  "a sandstorm sweeping across a road": "sandstorm dust highway desert wind visibility chaos wasteland",
  "a mountain peak above the clouds": "mountain peak summit clouds altitude climb achievement everest",
  "an hourglass running out of sand": "hourglass sand glass time deadline countdown urgency mortality",
  "an antique brass compass": "compass brass needle north direction navigation guidance explorer",
  "a pocket watch with open gears": "watch gears pocket clockwork time mechanism precision steampunk",
  "a skeleton key on a ribbon": "key ribbon skeleton lock door secret mystery access",
  "a candle melting in the dark": "candle wax flame dark melting midnight vigil prayer",
  "a paper lantern glowing": "lantern paper glow festival celebration float wish lunar",
  "a vintage typewriter": "typewriter keys paper writer novel journalism retro manuscript",
  "a crystal ball on a stand": "crystal ball stand fortune future psychic prophecy seer",
  "a magnifying glass over a map": "lens map search clue detective explore treasure investigation",
  "a broken mirror": "mirror glass shards reflection broken shattered luck curse",
  "a messy stack of old books": "books stack pages library knowledge study dusty scholar",
  "a quill pen and inkwell": "quill ink feather pen parchment letter writing poet",
  "a chess board mid-game": "chess board pawn king strategy tactics checkmate gambit",
  "a pair of dice mid-roll": "dice roll chance random gamble luck casino fate",
  "a music box with a tiny dancer": "music box ballerina dancer melody keepsake nostalgia lullaby",
  "a red umbrella in the rain": "umbrella rain red puddle shelter protection melancholy standout",
  "a deflated party balloon": "balloon party deflated rubber aftermath disappointment letdown hangover",
  "a pair of muddy boots": "boots mud dirt hiking farm work adventure trek",
  "a padlock with a heart on a bridge": "padlock heart bridge love romance commitment forever paris",
  "a rusty anchor": "anchor rust chain ship harbor sailor stability tattoo",
  "a telescope pointed at the sky": "telescope sky stars lens astronomy observatory discovery stargazing",
  "a gramophone with a large horn": "gramophone horn record vinyl music antique jazz phonograph",
  "a birdcage with the door open": "birdcage cage door bird freedom escape release liberation",
  "a spinning top": "top spin toy wobble momentum balance dizzy inception",
  "a kite tangled in a tree": "kite tree string tangled wind stuck childhood frustration",
  "an old film camera": "camera film lens shutter photograph memories vintage snapshot",
  "a jigsaw puzzle with one missing piece": "puzzle jigsaw piece missing incomplete solve mystery frustration",
  "a lit match": "match flame fire spark sulfur ignite beginning arson",
  "a message in a bottle": "bottle message ocean letter castaway shipwreck island hope",
  "a toolbox full of wrenches": "toolbox wrench tools garage repair fix mechanic handyman",
  "a sewing machine with thread": "sewing thread needle fabric stitch craft tailor seamstress",
  "a rocking chair on a porch": "rocking chair porch relax retirement country grandma nostalgia",
  "a lighthouse lens": "lens lighthouse beam glass prism guidance beacon signal",
  "a pile of gold coins": "gold coins treasure money wealth riches pirate greed",
  "a teapot pouring tea": "teapot tea pour porcelain steam afternoon british party",
  "a chandelier with candles": "chandelier candles crystal ballroom elegance luxury mansion opera",
  "a pair of scissors cutting ribbon": "scissors ribbon cut ceremony opening launch inauguration grand",
  "a fishing rod and a tiny fish": "fishing rod fish hook bait catch patience disappointment",
  "a bicycle leaning on a wall": "bicycle wheels wall pedal ride commute freedom city",
  "a snow globe with a little village": "globe snow village glass winter miniature christmas souvenir",
  "a pinata hanging from a tree": "pinata candy stick party birthday fiesta smash blindfold",
  "a mechanical robot toy": "robot toy tin gears windup machine automaton childhood",
  "a lava lamp": "lava lamp blobs wax groovy retro psychedelic hippie",
  "a rotary telephone": "telephone rotary dial receiver call landline retro operator",
  "a stopwatch": "stopwatch timer seconds race speed sprint countdown record",
  "a paintbrush dripping paint": "paintbrush paint drip canvas artist creativity color masterpiece",
  "a wooden ladder against a wall": "ladder wood rungs wall climb ascent progress career",
  "a pile of autumn pumpkins": "pumpkin orange patch harvest autumn halloween thanksgiving jack",
  "a sword stuck in a stone": "sword stone blade excalibur legend king destiny worthy",
  "a traffic light glowing red": "traffic light red signal intersection stop wait halt",
  "a slice of watermelon": "watermelon slice seeds rind summer picnic juicy refreshing",
  "a steaming bowl of ramen": "ramen noodles bowl broth chopsticks steam comfort slurp",
  "a towering birthday cake": "cake birthday candles frosting layers celebration party wish",
  "a pineapple wearing sunglasses": "pineapple sunglasses tropical beach summer vacation cool attitude",
  "a jar of honey with a dipper": "honey jar dipper golden sweet sticky hive sweetheart",
  "a basket of fresh bread": "bread basket loaf crust bakery oven dough nourishment",
  "a cup of hot cocoa with marshmallows": "cocoa marshmallows mug chocolate winter cozy warmth comfort",
  "a sliced lemon": "lemon citrus yellow juice sour zest lemonade tart",
  "a pizza fresh from the oven": "pizza oven cheese slice crust pepperoni delivery italy",
  "a bunch of purple grapes": "grapes purple vine vineyard wine harvest raisin sour",
  "a melting ice cream cone": "cone scoop drip melting summer dessert sweet heatwave",
  "a cracked egg with a golden yolk": "egg yolk shell crack breakfast golden fragile omelette",
  "a wedge of cheese with holes": "cheese wedge holes swiss dairy mouse mousetrap fondue",
  "a bowl of chili peppers": "chili peppers red spicy hot heat fire mexican",
  "a pile of sushi": "sushi rice fish seaweed chopsticks raw roll japanese",
  "a stack of pancakes with syrup": "pancakes syrup stack butter breakfast maple brunch fluffy",
  "a coconut split open": "coconut shell milk husk tropical palm island castaway",
  "a chocolate bar broken in half": "chocolate bar squares sweet share craving indulgence temptation",
  "a bowl of popcorn": "popcorn bowl butter kernels snack movie cinema drama",
  "a single red apple": "apple red fruit orchard teacher temptation eden newton",
  "a cup of espresso": "espresso coffee cup caffeine energy morning barista italy",
  "a pot of soup over a fire": "soup pot fire stew campfire hearth cauldron witch",
  "a candy cane": "candy cane peppermint stripes christmas holiday sweet festive",
  "a bunch of carrots fresh from the soil": "carrots soil garden roots vegetable harvest farm rabbit",
  "a lighthouse in a storm": "lighthouse storm waves coast beacon keeper guidance refuge",
  "an abandoned carousel": "carousel horses fairground abandoned forgotten eerie nostalgia childhood",
  "a medieval castle on a cliff": "castle cliff tower medieval fortress kingdom knight fairytale",
  "an ancient pyramid": "pyramid desert tomb pharaoh ancient egypt mummy mystery",
  "a neon-lit city street at night": "neon city street glow urban nightlife cyberpunk noir",
  "a cozy library with a fireplace": "library fireplace books armchair reading study cozy winter",
  "an underground subway station": "subway station underground train platform tunnel commute metro",
  "a sunken shipwreck": "shipwreck hull seabed barnacles treasure diver ghost titanic",
  "a treehouse in an oak tree": "treehouse oak ladder branches hideout fort childhood adventure",
  "a carnival ferris wheel": "ferris wheel carnival fair lights ride summer romance",
  "an empty theater stage with a spotlight": "stage spotlight theater curtain performance drama audition monologue",
  "a busy train station": "train station platform crowd commute departure journey rush",
  "a greenhouse full of plants": "greenhouse plants glass garden growth botany humid nursery",
  "a space station orbiting earth": "station space orbit earth satellite astronaut gravity frontier",
  "a desert oasis with palm trees": "oasis palm desert water refuge relief mirage caravan",
  "a snowy mountain cabin": "cabin snow mountain log chimney retreat cozy isolation",
  "a crowded open-air market": "market stalls crowd produce vendors commerce bazaar haggle",
  "an old windmill in a field": "windmill field blades farm grain flour dutch tilting",
  "a haunted house on a hill": "haunted house ghost hill spooky horror halloween creaky",
  "a venetian canal with gondolas": "gondola canal boat water venice italy romance serenade",
  "a bowling alley": "bowling pins ball lane strike spare league gutter",
  "a laundromat at midnight": "laundromat washing machine laundry midnight spin lonely insomnia",
  "a temple hidden in a jungle": "temple jungle vines ruins ancient lost explorer idol",
  "a bridge covered in fog": "bridge fog mist river crossing mystery uncertainty golden",
  "a quiet hospital corridor": "hospital corridor nurse doctor sterile waiting silence emergency",
  "a school classroom with a chalkboard": "classroom chalkboard chalk desk teacher school lesson education",
  "a submarine control room": "submarine periscope sonar controls depth dive navy pressure",
  "an airport runway at sunset": "runway airport plane sunset takeoff departure travel horizon",
  "a racetrack with cars speeding": "racetrack cars speed race lap formula checkered adrenaline",
  "a lonely gas station at night": "gas pump station highway fluorescent isolation roadtrip desolate",
  "a rooftop garden in a city": "rooftop garden city skyline plants urban green oasis",
  "an ice hotel": "ice hotel frozen sculpture igloo arctic luxury chill",
  "a bakery shop window": "bakery window pastries croissant bread display baker temptation",
  "a museum hall with dinosaur bones": "museum dinosaur bones fossil skeleton extinct history paleontology",
  "a stone labyrinth": "labyrinth maze stone walls lost puzzle escape minotaur",
  "a farm barn with hay bales": "barn hay bales farm tractor rural harvest country",
  "an igloo under the stars": "igloo stars snow ice arctic shelter night inuit",
  "a casino table with chips": "casino chips table poker gamble bet jackpot vegas",
  "a recording studio": "studio microphone headphones mixer recording album music track",
  "a water park slide": "slide water park pool splash summer thrill fun",
  "a magician pulling a rabbit from a hat": "magician rabbit hat wand magic trick illusion abracadabra",
  "an astronaut floating in space": "astronaut space helmet spacesuit weightless gravity cosmos moon",
  "a deep-sea diver with a lantern": "diver lantern helmet ocean depth pressure explore abyss",
  "a chef tossing vegetables in a pan": "chef pan vegetables wok kitchen cooking cuisine flair",
  "a knight in shining armor": "knight armor sword shield medieval chivalry hero rescue",
  "a ballerina mid-spin": "ballerina tutu pirouette ballet dance spin grace swan",
  "a firefighter holding a hose": "firefighter hose water helmet fire rescue bravery hero",
  "a detective in a trench coat": "detective fedora coat clue mystery sleuth noir sherlock",
  "a pirate with a treasure map": "pirate map treasure ship parrot plunder adventure buccaneer",
  "a beekeeper with a smoker": "beekeeper bees hive smoker veil honey apiary colony",
  "a mountain climber on a ridge": "climber ridge mountain rope summit altitude courage risk",
  "a street musician playing violin": "violin street musician strings busker melody sidewalk serenade",
  "a gardener watering plants": "gardener watering can plants garden growth nurture green",
  "a samurai under falling leaves": "samurai katana leaves sword honor warrior autumn japan",
  "a clown juggling": "clown juggle balls nose circus laughter balance chaos",
  "a scientist with bubbling flasks": "scientist flask lab bubbles chemistry experiment potion mad",
  "a lifeguard on a tower": "lifeguard tower beach whistle rescue swim watch baywatch",
  "a painter at an easel": "canvas brush palette art portrait creativity masterpiece bohemian",
  "a surfer riding a wave": "wave surfboard ocean balance thrill summer barrel tide",
  "a child building a sandcastle": "sand bucket beach childhood imagination kingdom moat fleeting",
  "a king on a golden throne": "crown gold throne royalty power monarch reign tyrant",
  "a librarian shushing": "books shelves glasses silence quiet reading hush whisper",
  "a marathon runner crossing the finish line": "ribbon sneakers sweat endurance victory race stamina triumph",
  "a fortune teller with tarot cards": "cards crystal shawl destiny future mystic prophecy omen",
  "a conductor leading an orchestra": "baton tuxedo podium symphony music harmony maestro crescendo",
  "a shepherd with sheep on a hill": "crook wool hill flock pastoral guardian lamb parable",
  "a skier racing downhill": "snow poles goggles speed winter alpine avalanche olympics",
  "a boxer in the ring": "gloves ring ropes fight punch champion knockout underdog",
  "an archer drawing a bow": "arrow quiver target aim focus precision bullseye sagittarius",
  "a mime trapped in an invisible box": "stripes beret gloves silence invisible performance pantomime trapped",
  "a hot air balloon over fields": "basket burner patchwork flight drift adventure voyage serenity",
  "a steam locomotive": "smoke rails coal journey industry express nostalgia whistle",
  "a paper boat in a puddle": "origami rain puddle childhood innocence fragile voyage dream",
  "a pirate ship with black sails": "mast cannon skull plunder treasure buccaneer mutiny outlaw",
  "a rocket launching": "flames smoke gantry space countdown exploration liftoff moonshot",
  "a vintage red convertible": "chrome cherry wheels freedom nostalgia cruising retro sixties",
  "a yellow school bus": "yellow wheels driver school children commute morning homework",
  "a sailboat on a calm sea": "sail mast horizon breeze serenity voyage regatta solitude",
  "a helicopter over the city": "rotor skyline rooftops rescue surveillance traffic chopper news",
  "a tractor plowing a field": "soil furrow mud farm harvest agriculture labor heartland",
  "a fire truck with ladder raised": "ladder hose siren emergency rescue firefighter hero blaze",
  "a canoe on a misty river": "paddle mist pine wilderness solitude journey stillness frontier",
  "a cable car over mountains": "cable gondola peaks altitude ascent panorama vertigo suspended",
  "a skateboard mid-trick": "wheels ramp concrete trick youth rebel ollie airborne",
  "a zeppelin in the clouds": "blimp airship helium clouds flight steampunk dirigible rock",
  "a motorcycle on a desert highway": "asphalt leather cactus freedom rebel journey horizon mirage",
  "a tank crossing mud": "mud armor treads cannon war battle juggernaut trench",
  "a sled on a snowy hill": "snow mittens toboggan winter childhood thrill rosebud holiday",
  "a dragon sleeping on treasure": "gold scales cave hoard greed fantasy legend slumber",
  "a unicorn in a misty forest": "horn mist forest magic purity myth rare enchanted",
  "a wizard tower in the clouds": "spire stone clouds magic sorcery wisdom spellbook ivory",
  "a mermaid on a rock": "tail scales waves siren myth ocean longing lure",
  "a phoenix rising from flames": "flames feathers ashes rebirth immortal resurrection comeback renewal",
  "a fairy with glowing wings": "wings glitter flowers magic wish sparkle folklore tooth",
  "a giant chess piece in a field": "grass statue board strategy surreal game checkmate pawn",
  "a floating island with waterfalls": "waterfall cliffs clouds levitation paradise fantasy utopia avatar",
  "a robot tending a garden": "metal flowers sprout nurture automation future android ecology",
  "a ghost in an old hallway": "corridor cobwebs portrait haunting spirit afterlife poltergeist boo",
  "a vampire castle at night": "turrets bats moonlight gothic blood darkness fangs count",
  "a genie coming out of a lamp": "lamp smoke brass wishes magic servant bottle rub",
  "a friendly sea monster": "tentacles waves fins ocean gentle myth loch kraken",
  "a golem made of stone": "stone boulder moss giant guardian clay creation folklore",
  "a tiny house inside a lightbulb": "filament glass miniature idea home electricity imagination cozy",
  "a clockwork bird": "gears brass spring mechanism invention song steampunk nightingale",
  "a portal glowing in a forest": "glow trees swirl gateway dimension teleport wardrobe mystery",
  "a witch flying on a broom": "broom hat moon magic flight halloween spell coven",
  "a centaur in a meadow": "hooves meadow bow myth hybrid gallop legend sagittarius",
  "a crystal sword": "blade hilt gem quest power legend prism destiny",
  "a cloud shaped like a sheep": "sky fluffy wool daydream imagination shapes counting sleep",
  "a door standing alone in a desert": "frame sand dunes mystery surreal threshold opportunity nowhere",
  "a whale swimming through the sky": "clouds sky fins dream surreal gentle giant song",
  "a mushroom village": "toadstool moss cottages gnomes fairytale tiny woodland elves",
  "an hourglass containing the ocean": "sand waves glass time eternity tide mortality infinity",
  "a stairway to the moon": "steps moon stars ascent ambition dream heaven reach",
  "a tree growing out of a book": "roots pages leaves knowledge growth wisdom imagination story",
  "a city inside a glass bottle": "glass skyscrapers cork miniature captive world isolation souvenir",
  "fireworks over a harbor": "sparks boats reflections celebration festival midnight independence spectacle",
  "a pillow fight with feathers": "feathers pillows bedroom sleepover chaos laughter childhood mayhem",
  "a tug of war on a beach": "rope sand teams strength struggle competition tension stalemate",
  "a campfire with marshmallows": "flames sticks logs camping stories warmth scouts toasting",
  "a snowball fight": "snow mittens fort winter battle ambush childhood truce",
  "a picnic blanket in a park": "blanket basket sandwiches grass leisure summer gingham ants",
  "a game of hide and seek": "closet curtain counting game childhood secret peekaboo ready",
  "a dance party with a disco ball": "mirrors lights sparkle dance groove nightclub seventies fever",
  "a parade with confetti": "confetti floats streamers crowd celebration carnival victory homecoming",
  "a yoga pose at sunrise": "mat sunrise stretch balance mindfulness zen calm namaste",
  "a soccer ball hitting a goal net": "net ball grass score victory football penalty glory",
  "a chess tournament": "board clock pieces strategy intellect competition checkmate grandmaster",
  "a sandcastle being washed away": "sand waves tide impermanence loss erosion fleeting vanity",
  "a birthday candle being blown out": "candle cake smoke wish celebration age party frosting",
  "a wedding cake being cut": "tiers knife frosting marriage love celebration vows bride",
  "a race of paper airplanes": "paper origami classroom flight glide competition mischief aviation",
  "a hammock between two palm trees": "palms sand rope relaxation vacation tropical paradise siesta",
  "a karaoke singer on stage": "microphone lyrics spotlight singing performance confidence idol encore",
  "a game of poker": "cards chips table gambling bluff luck casino ace",
  "a treasure hunt with a shovel": "shovel map chest adventure discovery gold pirate quest",
  "a heart made of red leaves": "leaves autumn crimson love romance nature valentine fall",
  "a crown on a velvet pillow": "jewels velvet gold royalty coronation heir succession regalia",
  "an eye inside a triangle": "pyramid dollar rays conspiracy secret providence illuminati surveillance",
  "a four-leaf clover": "green leaves meadow luck fortune rare charm leprechaun",
  "a yin yang made of stones": "pebbles black white balance harmony duality zen opposites",
  "a skull with roses": "skull roses thorns death mortality beauty tattoo gothic",
  "a white flag on a pole": "pole cloth wind surrender peace truce defeat ceasefire",
  "a trophy cup": "gold handles pedestal victory champion award glory winner",
  "a peace dove carrying an olive branch": "feathers olive branch peace hope harmony ark flood",
  "a broken chain": "links iron metal freedom liberation escape emancipation shackles",
  "a key and a lock": "padlock keyhole metal security secret access solution soulmate",
  "a balance scale": "weights pans brass justice fairness law libra equilibrium",
  "a question mark made of clouds": "clouds sky vapor mystery uncertainty curiosity doubt riddle",
  "an infinity sign drawn in sparklers": "sparks light night infinity eternity forever celebration loop",
  "a lightbulb turning on": "filament glass glow idea inspiration eureka genius epiphany",
  "an empty throne": "velvet gold hall power vacancy absence succession abdication",
  "a medal on a ribbon": "ribbon gold bronze honor achievement bravery olympics podium",
  "a maze seen from above": "hedges walls paths puzzle labyrinth confusion minotaur lost",
  "a crossroads sign post": "arrows wood road choice decision direction fork destiny",
  "a ticking time bomb": "fuse timer wires danger urgency explosion deadline countdown",
  "a raindrop hitting a puddle": "ripple splash water rain moment circles tears echo",
  "a foggy morning on a pier": "fog planks water solitude dawn mystery melancholy haze",
  "a snowman wearing a scarf": "carrot scarf coal winter christmas frosty childhood melting",
  "a heatwave over a city": "sun skyline asphalt heat summer sweat mirage inferno",
  "a hailstorm on a car": "ice dents windshield storm damage weather insurance barrage",
  "a windy day with flying hats": "hats gust leaves wind chaos autumn whirlwind slapstick",
  "icicles hanging from a roof": "ice eaves gutter winter cold freeze dagger stalactite",
  "a sunset over the ocean": "horizon waves orange dusk evening romance farewell golden",
  "storm clouds gathering": "thunder gray lightning storm foreboding trouble omen brewing",
  "a frosty window with drawings": "frost glass finger winter doodle childhood breath cozy",
  "a grand piano in an empty hall": "keys hall stage music solitude silence recital echo",
  "an electric guitar on fire": "flames strings amplifier rock music passion solo metal",
  "a drum kit": "cymbals sticks snare rhythm beat percussion band thunder",
  "a saxophone under a streetlight": "brass streetlight sidewalk jazz night blues noir melancholy",
  "a pair of headphones": "cord ears cushions music sound isolation playlist bass",
  "a violin with a broken string": "bow strings wood music heartbreak imperfection sorrow fiddle",
  "a vinyl record spinning": "turntable needle grooves music nostalgia retro spin album",
  "a church organ with tall pipes": "pipes keys cathedral hymn worship sacred phantom requiem",
  "a harp made of light": "strings glow rays music heaven angel ethereal celestial",
  "a trumpet with a bent bell": "brass valves dent jazz fanfare music dizzy battered",
  "a chameleon-headed man in a tailcoat dropping a paper into a ballot box": "lizard tailcoat ballot election democracy politics turncoat opportunist",
  "a magpie lady in an enormous crinoline writing with a quill": "quill ink gown writing correspondence gossip chatter bluestocking",
  "a spaniel in a frock coat holding a hunting horn behind his back": "horn coat ears hunt loyalty hound bugle gentry",
  "a rabbit gentleman in a jacket next to a table with a top hat and books": "ears hat books gentleman scholar magic wonderland bunny",
  "a hare in a jacket and trousers holding a top hat upside down": "hare rabbit hat jacket trousers magic ears gentleman",
  "a portly vulture landlord in a top hat and greatcoat leaning on a cane": "beak cane greatcoat landlord rent greed scavenger eviction",
  "a rooster dandy in a tailcoat posing with a riding crop": "comb crop tailcoat vanity pride cocky strut fop",
  "a crocodile in a top hat dabbing its eyes at a shop counter, a body at its feet": "handkerchief counter corpse hypocrisy murder insincerity tears mourning",
  "an insect gentleman in a tailcoat admiring a portrait on the wall": "insect antennae portrait painting frame tailcoat vanity gallery",
  "an old butterfly dandy sniffing a vase of flowers, hat in hand": "wings vase bouquet scent aging nostalgia flirt gallant",
  "a crow in a tailcoat hurrying down a city street": "feathers tailcoat cobblestones haste commute urban late undertaker",
  "an old animal veteran in a bicorne hat leaning on a sword": "bicorne sword uniform veteran war general glory retirement",
  "a stork in a judge’s black robe and white wig": "robe wig beak court law verdict gavel pompous",
  "a wolf chained in a prison cell, reading a book": "chains bars book prison redemption reform convict rehabilitation",
  "a little animal housemaid in a bonnet and apron": "bonnet apron broom servant chores domestic housework drudgery",
  "an old mouse seamstress in a long dress sitting in a wooden armchair": "needle thread armchair sewing granny patience tailor mousy",
  "a cat peering at mice trapped inside a cage": "cage whiskers bars prey predator hunger captivity temptation",
  "a long-beaked bird traveller with a backpack and walking stick": "backpack stick beak journey migration pilgrim wanderlust hiker",
  "a bird officer in a cocked hat, plaid cape and riding boots": "plaid cape boots officer military rank cavalry highlander",
  "a wolf standing guard in a cape, holding a rifle over his shoulder": "rifle cape fur sentry duty watch soldier predator",
  "a creature in a straw hat chasing butterflies with a net": "net straw butterflies summer chase collector naturalist folly",
  "a she-wolf lady in a grand ball gown": "gown fur ballroom elegance predator disguise seduction aristocrat",
  "a fox in an overcoat holding his top hat": "overcoat hat tail cunning sly gentleman trickster swindler",
  "a swaggering musketeer in a plumed hat and cape": "plume cape rapier bravado adventure duel swashbuckler cavalier",
  "a heron lady in a full dress carrying a handbag": "handbag dress legs elegance fashion shopping poise stilts",
  "a stork standing over a gathering of black birds by a stone column": "column stone crowd sermon assembly authority congregation murder",
  "a shrew in shirtsleeves drilling into the ground with a hand auger, a pickaxe at its feet": "shrew mouse drill auger pickaxe digging mining well",
  "an old falcon gentleman in a long coat and spotted waistcoat": "waistcoat polka coat gentleman dignity elder predator falconry",
  "a dog hunter with a rifle leaning on a fence": "rifle fence boots hunt countryside gamekeeper loyalty poacher",
  "a turkey banker in a suit fanning his huge tail": "suit plumage coins wealth capitalism pompous vanity tycoon",
  "an owl lady in a frilly ball gown": "gown frills eyes ballroom wisdom elegance night dowager",
  "an old bird servant in a coat, hands clasped behind its back": "coat beak posture butler loyalty duty patience discretion",
  "an open pocket knife standing upright like a person, casting a long shadow": "blade shadow steel menace danger sharp lurking noir",
  "two quill pens with faces fighting a sword duel": "quill ink feathers duel rivalry debate critics mightier",
  "a walking pen nib carrying a bundle and a pennant toward the rising sun": "nib pennant bindle sunrise journey pilgrimage hope crusade",
  "a grinning one-eyed gentleman with an eye patch and crossed legs, holding his hat": "grin patch pirate eye hat smug rascal showman",
  "steam engines making music: one blows a trumpet, another reads a score": "trumpet score pistons music industry machines cacophony revolution",
  "a steam machine playing the harp beside a baby’s cradle": "harp cradle steam lullaby automation nanny nursery progress",
  "a tall monument column surrounded by a swirl of tiny people, coaches and objects": "column monument carriages crowd chaos vortex bustle babel",
  "rabbits and a fox dancing wildly while a bird in a cloak watches": "bunnies fox cloak dance revelry frenzy bacchanal truce",
  "a ballerina with dragonfly wings dancing on tiptoe": "wings tutu slippers ballet grace pirouette fairy delicate",
  "leaping ballerinas in front of a row of disembodied dancing legs": "legs tutus stage ballet chorus surreal cancan cabaret",
  "a jointed wooden marionette dancer with too many arms and legs": "wood joints limbs puppet strings dance manipulation octopus",
  "two vegetable gentlemen with leafy heads fighting a duel with long spears": "leaves spears cabbage joust duel rivalry salad chivalry",
  "a huge dog walking a tiny man in a top hat on a leash": "leash collar hat reversal master obedience satire absurd",
  "a monkey painter at an easel while another monkey watches": "easel canvas brush art critic apprentice mimicry studio",
  "monkeys in a painting studio, one working on a huge canvas while others copy him": "canvas studio brushes imitation plagiarism academy forgery copycat",
  "a gigantic thumb and fist carved as statues, with a tiny sculptor at work": "thumb fist chisel marble sculpture colossus monument approval",
  "a black sun with long rays rising over the mountains": "rays peaks sunrise eclipse darkness omen apocalypse melancholy",
  "a frog flying on enormous eagle wings": "wings feathers pond flight ambition hybrid leap chimera",
  "a toucan ridden by a goblin chasing a bear and a tortoise while strange birds fly overhead": "beak goblin tortoise chase hunt menagerie bestiary rodeo",
  "a zoo enclosure with a giraffe, a stork, an owl, a tortoise and odd creatures": "giraffe fence owl captivity exhibit collection menagerie ark",
  "a landscape of crystals, pyramids, towers and dice": "crystals pyramids dice geometry chance surreal abstract gamble",
  "a clifftop garden of plants shaped like feathers, combs, shells and brushes": "feathers combs shells cliff botany surreal grooming flora",
  "a spidery acrobat walking a tightrope above a field of flowers": "rope flowers legs balance circus daring risk web",
  "flowers with faces walking out through an arched doorway": "petals arch stems spring procession exodus escape bloom",
  "vegetables and flowers with faces holding a meeting": "vegetables flowers leaves council debate committee parliament bureaucracy",
  "a man floating above the clouds held up by kites": "kites clouds strings flight dream freedom levity escapism",
  "a man flying with giant feather wings strapped to his body": "wings feathers straps flight invention ambition icarus hubris",
  "an impossibly tall, thin man looming over a seated woman": "lanky chair shadow intimidation dominance menace beanpole skyscraper",
  "a lyre with a smiling face, framed by laurel branches and rays of light": "strings laurel rays music poetry harmony muse ode",
  "a cupid leaning on a walking stick beside a butterfly": "cane butterfly wings love aging romance cherub valentine",
  "a cow-headed idol seated on a pedestal in clouds of smoke": "horns pedestal incense worship idolatry sacred cult calf",
  "a giant clock machine above a grumpy giant, with tiny men riding seesaws": "clock gears seesaws time machinery giant contraption absurdity",
  "a tiny dancer suspended between two enormous fan-like leaves": "leaves fronds ballerina dance grace balance miniature ethereal",
  "officers in plumed hats scrambling over each other up a ladder, waving papers": "ladder plumes papers ambition promotion hierarchy bureaucracy careerist",
  "a great wheel of hats spinning through the years": "hats wheel bonnets fashion cycle history trends carousel",
  "giant letters standing like a gateway, a tiny figure balancing on top": "letters alphabet gate typography balance language literacy acrobat",
};
