// Visual concepts used to build image prompts. Each entry should describe something that
// can be drawn clearly and that invites several associations (literal, cultural, metaphorical…).

import { SURREAL_BANK } from './surrealBank';

export { SURREAL_BANK };

export interface Concept {
  text: string;
  category: string;
}

const RAW: Record<string, string[]> = {
  animals: [
    'an owl perched on a branch at dusk',
    'a jellyfish glowing in dark water',
    'a red fox curled up in snow',
    'a peacock displaying its tail',
    'a chameleon on a twig',
    'a humpback whale breaching',
    'a hummingbird drinking from a flower',
    'a sleeping cat on a windowsill',
    'a pack of wolves howling at the moon',
    'an elephant crossing a river',
    'a penguin sliding on ice',
    'a tortoise with moss on its shell',
    'a flamingo standing on one leg',
    'a honeybee on a sunflower',
    'a spider web covered in dew',
    'a lion resting on a rock',
    'a giraffe eating from a tall tree',
    'a goldfish in a round bowl',
    'a raven on a fence post',
    'a snail climbing a mushroom',
    'a polar bear on drifting ice',
    'an octopus holding a seashell',
    'a monarch butterfly on a leaf',
    'a parrot with bright feathers',
    'a camel in the desert',
    'a rabbit in tall grass',
    'a seahorse among coral',
    'a bat hanging upside down in a cave',
    'a swan gliding on a lake',
    'a dog catching a frisbee',
    'a frog on a lily pad',
    'a horse galloping through surf',
    'a sloth hanging from a branch',
    'a squirrel holding an acorn',
    'a shark fin cutting through waves',
    'a firefly glowing in the night',
    'a crab on a sandy beach',
    'a dragonfly over a pond',
  ],
  nature: [
    'a volcano erupting at night',
    'a rainbow over green hills',
    'a giant redwood forest',
    'a frozen waterfall',
    'a lightning storm over the plains',
    'a desert with rippling sand dunes',
    'a coral reef full of fish',
    'the northern lights over mountains',
    'a single cactus flower in bloom',
    'a field of sunflowers',
    'an iceberg floating in the sea',
    'autumn leaves falling in a park',
    'a tornado on the horizon',
    'a crystal cave glittering',
    'a quiet bamboo grove',
    'cherry blossoms in spring',
    'a solar eclipse',
    'a meteor shower over a lake',
    'a tide pool with starfish',
    'a giant ocean wave curling',
    'a mossy stone in a stream',
    'a snowflake under magnification',
    'a full moon behind clouds',
    'a lone tree on a hill',
    'a misty swamp at dawn',
    'a canyon with layered red rock',
    'a geyser erupting',
    'a garden of roses',
    'a sandstorm sweeping across a road',
    'a mountain peak above the clouds',
  ],
  objects: [
    'an hourglass running out of sand',
    'an antique brass compass',
    'a pocket watch with open gears',
    'a skeleton key on a ribbon',
    'a candle melting in the dark',
    'a paper lantern glowing',
    'a vintage typewriter',
    'a crystal ball on a stand',
    'a magnifying glass over a map',
    'a broken mirror',
    'a messy stack of old books',
    'a quill pen and inkwell',
    'a chess board mid-game',
    'a pair of dice mid-roll',
    'a music box with a tiny dancer',
    'a red umbrella in the rain',
    'a deflated party balloon',
    'a pair of muddy boots',
    'a padlock with a heart on a bridge',
    'a rusty anchor',
    'a telescope pointed at the sky',
    'a gramophone with a large horn',
    'a birdcage with the door open',
    'a spinning top',
    'a kite tangled in a tree',
    'an old film camera',
    'a jigsaw puzzle with one missing piece',
    'a lit match',
    'a message in a bottle',
    'a toolbox full of wrenches',
    'a sewing machine with thread',
    'a rocking chair on a porch',
    'a lighthouse lens',
    'a pile of gold coins',
    'a teapot pouring tea',
    'a chandelier with candles',
    'a pair of scissors cutting ribbon',
    'a fishing rod and a tiny fish',
    'a bicycle leaning on a wall',
    'a snow globe with a little village',
    'a pinata hanging from a tree',
    'a mechanical robot toy',
    'a lava lamp',
    'a rotary telephone',
    'a stopwatch',
    'a paintbrush dripping paint',
    'a wooden ladder against a wall',
    'a pile of autumn pumpkins',
    'a sword stuck in a stone',
    'a traffic light glowing red',
  ],
  food: [
    'a slice of watermelon',
    'a steaming bowl of ramen',
    'a towering birthday cake',
    'a pineapple wearing sunglasses',
    'a jar of honey with a dipper',
    'a basket of fresh bread',
    'a cup of hot cocoa with marshmallows',
    'a sliced lemon',
    'a pizza fresh from the oven',
    'a bunch of purple grapes',
    'a melting ice cream cone',
    'a cracked egg with a golden yolk',
    'a wedge of cheese with holes',
    'a bowl of chili peppers',
    'a pile of sushi',
    'a stack of pancakes with syrup',
    'a coconut split open',
    'a chocolate bar broken in half',
    'a bowl of popcorn',
    'a single red apple',
    'a cup of espresso',
    'a pot of soup over a fire',
    'a candy cane',
    'a bunch of carrots fresh from the soil',
  ],
  places: [
    'a lighthouse in a storm',
    'an abandoned carousel',
    'a medieval castle on a cliff',
    'an ancient pyramid',
    'a neon-lit city street at night',
    'a cozy library with a fireplace',
    'an underground subway station',
    'a sunken shipwreck',
    'a treehouse in an oak tree',
    'a carnival Ferris wheel',
    'an empty theater stage with a spotlight',
    'a busy train station',
    'a greenhouse full of plants',
    'a space station orbiting earth',
    'a desert oasis with palm trees',
    'a snowy mountain cabin',
    'a crowded open-air market',
    'an old windmill in a field',
    'a haunted house on a hill',
    'a Venetian canal with gondolas',
    'a bowling alley',
    'a laundromat at midnight',
    'a temple hidden in a jungle',
    'a bridge covered in fog',
    'a quiet hospital corridor',
    'a school classroom with a chalkboard',
    'a submarine control room',
    'an airport runway at sunset',
    'a racetrack with cars speeding',
    'a lonely gas station at night',
    'a rooftop garden in a city',
    'an ice hotel',
    'a bakery shop window',
    'a museum hall with dinosaur bones',
    'a stone labyrinth',
    'a farm barn with hay bales',
    'an igloo under the stars',
    'a casino table with chips',
    'a recording studio',
    'a water park slide',
  ],
  people: [
    'a magician pulling a rabbit from a hat',
    'an astronaut floating in space',
    'a deep-sea diver with a lantern',
    'a chef tossing vegetables in a pan',
    'a knight in shining armor',
    'a ballerina mid-spin',
    'a firefighter holding a hose',
    'a detective in a trench coat',
    'a pirate with a treasure map',
    'a beekeeper with a smoker',
    'a mountain climber on a ridge',
    'a street musician playing violin',
    'a gardener watering plants',
    'a samurai under falling leaves',
    'a clown juggling',
    'a scientist with bubbling flasks',
    'a lifeguard on a tower',
    'a painter at an easel',
    'a surfer riding a wave',
    'a child building a sandcastle',
    'a king on a golden throne',
    'a librarian shushing',
    'a marathon runner crossing the finish line',
    'a fortune teller with tarot cards',
    'a conductor leading an orchestra',
    'a shepherd with sheep on a hill',
    'a skier racing downhill',
    'a boxer in the ring',
    'an archer drawing a bow',
    'a mime trapped in an invisible box',
  ],
  vehicles: [
    'a hot air balloon over fields',
    'a steam locomotive',
    'a paper boat in a puddle',
    'a pirate ship with black sails',
    'a rocket launching',
    'a vintage red convertible',
    'a yellow school bus',
    'a sailboat on a calm sea',
    'a helicopter over the city',
    'a tractor plowing a field',
    'a fire truck with ladder raised',
    'a canoe on a misty river',
    'a cable car over mountains',
    'a skateboard mid-trick',
    'a zeppelin in the clouds',
    'a motorcycle on a desert highway',
    'a tank crossing mud',
    'a sled on a snowy hill',
  ],
  fantasy: [
    'a dragon sleeping on treasure',
    'a unicorn in a misty forest',
    'a wizard tower in the clouds',
    'a mermaid on a rock',
    'a phoenix rising from flames',
    'a fairy with glowing wings',
    'a giant chess piece in a field',
    'a floating island with waterfalls',
    'a robot tending a garden',
    'a ghost in an old hallway',
    'a vampire castle at night',
    'a genie coming out of a lamp',
    'a friendly sea monster',
    'a golem made of stone',
    'a tiny house inside a lightbulb',
    'a clockwork bird',
    'a portal glowing in a forest',
    'a witch flying on a broom',
    'a centaur in a meadow',
    'a crystal sword',
    'a cloud shaped like a sheep',
    'a door standing alone in a desert',
    'a whale swimming through the sky',
    'a mushroom village',
    'an hourglass containing the ocean',
    'a stairway to the moon',
    'a tree growing out of a book',
    'a city inside a glass bottle',
  ],
  activities: [
    'fireworks over a harbor',
    'a pillow fight with feathers',
    'a tug of war on a beach',
    'a campfire with marshmallows',
    'a snowball fight',
    'a picnic blanket in a park',
    'a game of hide and seek',
    'a dance party with a disco ball',
    'a parade with confetti',
    'a yoga pose at sunrise',
    'a soccer ball hitting a goal net',
    'a chess tournament',
    'a sandcastle being washed away',
    'a birthday candle being blown out',
    'a wedding cake being cut',
    'a race of paper airplanes',
    'a hammock between two palm trees',
    'a karaoke singer on stage',
    'a game of poker',
    'a treasure hunt with a shovel',
  ],
  symbols: [
    'a heart made of red leaves',
    'a crown on a velvet pillow',
    'an eye inside a triangle',
    'a four-leaf clover',
    'a yin yang made of stones',
    'a skull with roses',
    'a white flag on a pole',
    'a trophy cup',
    'a peace dove carrying an olive branch',
    'a broken chain',
    'a key and a lock',
    'a balance scale',
    'a question mark made of clouds',
    'an infinity sign drawn in sparklers',
    'a lightbulb turning on',
    'an empty throne',
    'a medal on a ribbon',
    'a maze seen from above',
    'a crossroads sign post',
    'a ticking time bomb',
  ],
  weather: [
    'a raindrop hitting a puddle',
    'a foggy morning on a pier',
    'a snowman wearing a scarf',
    'a heatwave over a city',
    'a hailstorm on a car',
    'a windy day with flying hats',
    'icicles hanging from a roof',
    'a sunset over the ocean',
    'storm clouds gathering',
    'a frosty window with drawings',
  ],
  music: [
    'a grand piano in an empty hall',
    'an electric guitar on fire',
    'a drum kit',
    'a saxophone under a streetlight',
    'a pair of headphones',
    'a violin with a broken string',
    'a vinyl record spinning',
    'a church organ with tall pipes',
    'a harp made of light',
    'a trumpet with a bent bell',
  ],
};

/** Single scenes, one subject each (closer to classic picture cards). */
export const SCENE_BANK: readonly Concept[] = Object.entries(RAW).flatMap(([category, items]) =>
  items.map((text) => ({ text, category })),
);

export type ConceptSetId = 'surreal' | 'scenes';

export const CONCEPT_SETS: readonly { id: ConceptSetId; label: string; description: string }[] = [
  { id: 'surreal', label: 'Surreal mashups', description: 'Every picture fuses two things, like Codenames Pictures.' },
  { id: 'scenes', label: 'Single scenes', description: 'One clear subject or scene per picture.' },
];

export function conceptBank(id: ConceptSetId | string): readonly Concept[] {
  return id === 'scenes' ? SCENE_BANK : SURREAL_BANK;
}

/** Every known concept (used to find replacements after a content-filter rejection). */
export const CONCEPT_BANK: readonly Concept[] = [...SURREAL_BANK, ...SCENE_BANK];
