// Codenames Pictures-style subjects: every card fuses two (or more) ordinary things into one
// surreal picture, so a single image can answer to several different clues.
// All concepts are original to Open Codenames.

import type { Concept } from './conceptBank';

const RAW: Record<string, string[]> = {
  animals: [
    'an elephant whose trunk is an umbrella and whose tail is a propeller',
    'a snail whose shell is a lighthouse',
    'a giraffe whose neck is a wooden ladder',
    'an octopus whose tentacles are garden hoses',
    'a peacock whose tail feathers are playing cards',
    'an owl with alarm clocks for eyes',
    'a turtle carrying a castle on its back',
    'a whale whose spout is a fountain of coins',
    'a cat whose tail is a feather duster',
    'a goldfish swimming inside a light bulb',
    'a rabbit popping out of a toaster',
    'a penguin riding a unicycle on a tightrope',
    'a hedgehog whose spines are pencils',
    'a crocodile with a zipper down its back',
    'a flamingo standing on a pogo stick',
    'a bee whose wings are helicopter rotors',
    'a spider knitting a scarf with eight needles',
    'a dog wearing an old diving helmet',
    'a bat hanging upside down from a chandelier',
    'a camel whose humps are hot air balloons',
    'a horse with roller skates instead of hooves',
    'a crab whose claws are scissors',
    'a lion whose mane is a sunflower',
    'a bird nesting inside a top hat',
    'a sloth hanging from a ceiling fan',
    'a squirrel hoarding light bulbs',
    'a chameleon blending into a chessboard',
    'a swan made of folded newspaper',
    'a frog using a mushroom as an umbrella',
    'a mouse driving a cheese wheel like a car',
  ],
  objects: [
    'a teapot that is also a hot air balloon',
    'a light bulb with a tiny thunderstorm inside',
    'an hourglass filled with ocean waves',
    'a grand piano whose keys form a staircase',
    'a pocket watch melting over a cactus',
    'a sneaker with bird wings',
    'a toaster launching a rocket',
    'an umbrella raining upwards',
    'a giant key that is also a guitar',
    'a chess knight galloping out of an open book',
    'a coffee cup with a whirlpool inside',
    'a birdcage holding a cloud',
    'a ladder leaning against the crescent moon',
    'a candle whose flame is a goldfish',
    'a typewriter typing out butterflies',
    'a padlock with a tiny front door in it',
    'a telescope made of stacked teacups',
    'a magnifying glass showing a tiny city',
    'a pencil launching like a rocket',
    'a crown made of forks and spoons',
    'a mailbox with a small dragon living inside',
    'an anchor tied to a party balloon',
    'a broom sweeping up stars',
    'a compass whose needle is a fish',
    'an alarm clock with legs running away',
    'a paintbrush painting its own shadow',
    'a television with real water spilling out of it',
    'a pair of scissors cutting a cloud in half',
    'a trumpet blowing soap bubbles',
    'a bathtub sailing as a boat',
    'a refrigerator with a snowy mountain inside',
    'a vending machine selling planets',
    'an armchair growing tree roots',
    'a book with a waterfall pouring from its pages',
    'an old radio sprouting flowers',
    'a camera whose lens is a human eye',
    'an envelope with wings',
    'a boot that is a little house with a chimney',
    'a teacup with a sailing ship in a storm',
    'a light bulb hatching from an egg',
    'a sandwich with piano keys as the filling',
    'a fishbowl worn as a space helmet',
  ],
  places: [
    'a lighthouse that is a giant pencil',
    'a castle built on a cloud tied down with a rope',
    'a windmill whose blades are spoons',
    'a cottage walking on chicken legs',
    'a skyscraper made of stacked books',
    'a pyramid made of ice cream scoops',
    'a bridge made of piano keys',
    'a volcano erupting popcorn',
    'an island on the back of a whale',
    'a snow globe with a tiny city inside',
    'a tree house inside a giant mushroom',
    'a door standing alone in the ocean',
    'a spiral staircase climbing into the clouds',
    'a carousel with fish instead of horses',
    'a tent made of one giant leaf',
    'a fountain pouring out of a teapot',
  ],
  people: [
    'a knight in armor riding a giant snail',
    'an astronaut fishing from the moon',
    'a deep sea diver walking a dog on the seabed',
    'a chef juggling planets',
    'a magician pulling a dragon out of a hat',
    'a scarecrow conducting an orchestra of crows',
    'a ballerina spinning on a record player',
    'a king whose crown is a birdcage',
    'a robot watering a single flower',
    'a detective inspecting a giant fingerprint',
    'a pirate looking through a baguette telescope',
    'a mermaid relaxing in a bathtub',
    'a snowman sunbathing on a beach',
    'a samurai slicing a flying watermelon',
    'a mime trapped inside a light bulb',
    'a firefighter hosing down a sleepy dragon',
    'a sumo wrestler balancing on a teacup',
    'a wizard whose beard is a waterfall',
    'a cowboy riding a giant rubber duck',
    'a mountain climber scaling a stack of pancakes',
  ],
  food: [
    'a pineapple wearing a crown and a cape',
    'a slice of watermelon used as a boat',
    'a strawberry wearing roller skates',
    'a donut used as a life ring',
    'an egg cracking open to reveal a planet',
    'a carrot launching like a rocket',
    'a banana used as a telephone',
    'an ice cream cone with a volcano on top',
    'a burger with a jungle growing inside',
    'a lemon that is a submarine',
    'a fork twirling a spaghetti tornado',
    'a cake shaped like a castle besieged by ants',
    'a pizza used as a wall clock',
    'a wedge of cheese that is a mountain with climbers',
    'a cup of tea with an iceberg floating in it',
  ],
  vehicles: [
    'a bicycle whose wheels are pizzas',
    'a submarine whose periscope is a giraffe',
    'a sailboat with a sail made of a newspaper',
    'a steam train whose carriages are books',
    'a hot air balloon that is a jellyfish',
    'a car walking on legs instead of wheels',
    'a helicopter whose rotor is a ceiling fan',
    'a skateboard pulled by snails',
    'a tractor plowing the clouds',
    'a paper airplane with a jet engine',
    'a shopping cart with sails',
    'a rowing boat floating in the sky on a balloon',
  ],
  nature: [
    'a tree whose leaves are light bulbs',
    'a cactus wearing boxing gloves',
    'a cloud raining keys',
    'a rainbow pouring out of a faucet',
    'a sunflower whose center is a clock face',
    'a mountain with a zipper opening up',
    'the moon being peeled like an orange',
    'a tornado made of books',
    'an ocean wave shaped like a hand',
    'a flower growing out of an old boot',
    'a leaf whose veins are city streets',
    'a snowflake used as a wagon wheel',
  ],
  music: [
    'a guitar with a fishing reel',
    'a drum kit made of pots and pans',
    'a violin whose bow is a fishing rod',
    'a saxophone blooming with flowers',
    'a gramophone horn that is a giant seashell',
    'a microphone sprouting roots',
    'headphones made of a rainbow',
    'a harp whose strings are falling rain',
  ],
  sports: [
    'a soccer ball hatching from an egg',
    'a bowling pin wearing a top hat',
    'a basketball hoop on top of a lighthouse',
    'a chessboard floating on the sea',
    'a tennis racket used as a snowshoe',
    'a boxing glove with a bird nest inside',
    'a golf ball that is a tiny planet with a flag',
    'a trophy cup overflowing with spaghetti',
  ],
  tech: [
    'a computer mouse with a real mouse tail',
    'a robot arm writing with a quill pen',
    'a satellite dish catching raindrops',
    'a battery powering a sunflower',
    'a horseshoe magnet pulling down the moon',
    'a light switch on the trunk of a tree',
    'a laptop whose screen is a window to the sea',
    'a smartphone with a garden growing on it',
  ],
  fantasy: [
    'a dragon whose wings are umbrellas',
    'a unicorn whose horn is an ice cream cone',
    'a genie rising out of a coffee pot',
    'a ghost wearing a raincoat and rubber boots',
    'a giant chess pawn wearing a crown',
    'a crystal ball with a storm inside',
    'a treasure chest overflowing with stars',
    'a phoenix rising out of a toaster',
    'a castle inside a teacup',
    'a time machine made from a grandfather clock',
  ],
};

export const SURREAL_BANK: readonly Concept[] = Object.entries(RAW).flatMap(([category, items]) =>
  items.map((text) => ({ text, category })),
);
